CREATE TABLE SESHA_QUOTAS_CONFIG (
    BIZ_ID VARCHAR(255) PRIMARY KEY,
    QUOTA_ID VARCHAR(255),
    TAG_NAME VARCHAR(255),
    TAG_VALUE FLOAT,
    VALID INT DEFAULT 1,
    CID BIGINT,
	ALARM_NAME VARCHAR(255),
);